### ISSUE TITLE
Addnode

### ISSUE THREAD

**Issue by le2Ks** [UCDCOIN/UCDCOIN#1]
Hello, is there any addnode? 
The one in code: "node1.walletbuilders.com"  doesn't seem to be online.
Thx

**Comment by le2Ks** [comment]
EDIT: nevermind it's connecting now! Ty

**Comment by rakibulinux** [comment]
I am not getting any blocks. It's still showing 0. Also I am getting this log: The one in code: "node1.walletbuilders.com" doesn't seem to be online.

unitedcontinentaldollar-cli getblockchaininfo
{
  "chain": "main",
  "blocks": 0,
  "headers": 0,
  "bestblockhash": "000006438ae5b49979be5037e501dbf31e00a060a060e6bc5f852ff8526ac22c",
  "difficulty": 0.000244140625,
  "mediantime": 1635485066,
  "verificationprogress": 1,
  "initialblockdownload": false,
  "chainwork": "0000000000000000000000000000000000000000000000000000000000100010",
  "size_on_disk": 253,
  "pruned": false,
  "softforks": {
    "bip34": {
      "type": "buried",
      "active": true,
      "height": 0
    },
    "bip66": {
      "type": "buried",
      "active": true,
      "height": 0
    },
    "bip65": {
      "type": "buried",
      "active": true,
      "height": 0
    },
    "csv": {
      "type": "buried",
      "active": true,
      "height": 0
    },
    "segwit": {
      "type": "buried",
      "active": true,
      "height": 0
    }
  },
  "warnings": ""
}
